#!/usr/bin/env Rscript
# =============================================================================
# pam50_coverage.R
# =============================================================================
#
# PURPOSE:
# This script computes PAM50 gene coverage for each feature selection method
# used in the unsupervised feature selection pipeline. It reads gene lists
# generated by fs_wcgna.R and compares them against PAM50 gene signatures.
#
# PAM50 is a 50-gene signature used for breast cancer subtype classification:
#   - Luminal A, Luminal B, HER2-enriched, Basal-like, Normal-like
#
# Coverage metrics:
#   - Number of PAM50 genes found in each method's gene set
#   - Coverage fraction (intersection / 50)
#   - Coverage percentage
#   - List of matched PAM50 genes
#
# INPUTS:
#   --results_dir : Directory containing feature selection output files
#   --pam50_ensembl : Path to PAM50 Ensembl IDs file (one per line)
#   --pam50_symbols : Path to PAM50 gene symbols file (one per line, optional)
#
# OUTPUTS:
#   - pam50_coverage_by_method.tsv : Coverage table for all methods
#   - pam50_coverage_summary.txt : Summary statistics
#   - pam50_matches_per_method.tsv : Detailed matches for each method
#
# USAGE:
#   Rscript pam50_coverage.R \
#     --results_dir results/ \
#     --pam50_ensembl data/pam50_ensembl_ids.txt \
#     --pam50_symbols data/pam50_genes.txt
#
# =============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(purrr)
  library(stringr)
  library(readr)
})

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

read_gene_list_txt <- function(path) {
  # Reads a one-gene-per-line file, trims whitespace, drops empties and duplicates
  if (!file.exists(path)) {
    warning("File not found: ", path)
    return(character(0))
  }
  x <- readLines(path, warn = FALSE, encoding = "UTF-8")
  x <- str_trim(x)
  x <- x[x != ""]
  unique(x)
}

standardize_ensembl <- function(x) {
  # Standardize Ensembl IDs:
  # - Remove version suffixes (e.g., ENSG00000141510.1 -> ENSG00000141510)
  # - Trim whitespace
  # - Convert to uppercase
  x <- str_trim(x)
  x <- toupper(x)
  # Remove version suffix if present (e.g., .1, .2, etc.)
  x <- str_replace(x, "\\.\\d+$", "")
  x
}

standardize_symbols <- function(x) {
  # Standardize gene symbols:
  # - Trim whitespace
  # - Convert to uppercase
  x <- str_trim(x)
  x <- toupper(x)
  x
}

pam50_coverage <- function(gene_set, pam50_ensembl, pam50_symbols = NULL, 
                           gene_set_type = "ensembl") {
  # Compute PAM50 coverage for a gene set
  #
  # PARAMETERS:
  #   gene_set : Character vector of gene identifiers
  #   pam50_ensembl : Character vector of PAM50 Ensembl IDs
  #   pam50_symbols : Optional character vector of PAM50 gene symbols
  #   gene_set_type : "ensembl" or "symbol" - type of identifiers in gene_set
  #
  # RETURNS:
  #   Tibble with coverage metrics
  
  gene_set <- unique(gene_set)
  pam50_ensembl <- unique(standardize_ensembl(pam50_ensembl))
  
  # Standardize gene set based on type
  if (gene_set_type == "ensembl") {
    gene_set_std <- standardize_ensembl(gene_set)
    inter_ensembl <- intersect(gene_set_std, pam50_ensembl)
    inter <- inter_ensembl
  } else {
    # If gene_set contains symbols, we can only match if pam50_symbols provided
    if (is.null(pam50_symbols) || length(pam50_symbols) == 0) {
      return(tibble(
        pam50_size = length(pam50_ensembl),
        set_size = length(gene_set),
        pam50_in_set_n = 0L,
        pam50_coverage = 0.0,
        pam50_coverage_pc = 0.0,
        pam50_hits = ""
      ))
    }
    gene_set_std <- standardize_symbols(gene_set)
    pam50_symbols_std <- unique(standardize_symbols(pam50_symbols))
    inter_symbols <- intersect(gene_set_std, pam50_symbols_std)
    inter <- inter_symbols
  }
  
  coverage <- if (length(pam50_ensembl) == 0) {
    NA_real_
  } else {
    length(inter) / length(pam50_ensembl)
  }
  
  tibble(
    pam50_size = length(pam50_ensembl),
    set_size = length(gene_set),
    pam50_in_set_n = length(inter),
    pam50_coverage = coverage,
    pam50_coverage_pc = 100 * coverage,
    pam50_hits = paste(sort(inter), collapse = ", ")
  )
}

# =============================================================================
# MAIN SCRIPT
# =============================================================================

# Parse command-line arguments (simple approach)
args <- commandArgs(trailingOnly = TRUE)

# Default paths (can be overridden by command-line args)
results_dir <- "/work/ugbogu/expr_transformer/fs/results"
pam50_ensembl_file <- "/work/ugbogu/expr_transformer/data/pam50_ensembl_ids.txt"
pam50_symbols_file <- "/work/ugbogu/expr_transformer/data/pam50_genes.txt"

# Simple argument parsing
if (length(args) > 0) {
  arg_names <- c("--results_dir", "--pam50_ensembl", "--pam50_symbols")
  for (i in seq_along(args)) {
    if (args[i] %in% arg_names && i < length(args)) {
      val <- args[i + 1]
      if (args[i] == "--results_dir") results_dir <- val
      if (args[i] == "--pam50_ensembl") pam50_ensembl_file <- val
      if (args[i] == "--pam50_symbols") pam50_symbols_file <- val
    }
  }
}

cat("=== PAM50 Coverage Analysis ===\n")
cat("Results directory:", results_dir, "\n")
cat("PAM50 Ensembl file:", pam50_ensembl_file, "\n")
cat("PAM50 symbols file:", pam50_symbols_file, "\n\n")

# =============================================================================
# LOAD PAM50 GENE LISTS
# =============================================================================

pam50_ensembl <- read_gene_list_txt(pam50_ensembl_file)
pam50_symbols <- read_gene_list_txt(pam50_symbols_file)

cat("Loaded PAM50 genes:\n")
cat("  Ensembl IDs:", length(pam50_ensembl), "\n")
cat("  Gene symbols:", length(pam50_symbols), "\n\n")

if (length(pam50_ensembl) == 0 && length(pam50_symbols) == 0) {
  stop("No PAM50 genes loaded! Check file paths.")
}

# =============================================================================
# DEFINE GENE LIST FILES FROM FEATURE SELECTION OUTPUT
# =============================================================================

# Top 500 gene lists (final selections)
gene_files_top500 <- list(
  Variance   = file.path(results_dir, "top3000_variance.txt"),
  MAD        = file.path(results_dir, "top3000_MAD.txt"),
  MeanAbsDev = file.path(results_dir, "top3000_meanAbsDev.txt"),
  Entropy    = file.path(results_dir, "top3000_entropy.txt"),
  PCA        = file.path(results_dir, "top3000_PCAloadings.txt"),
  Spearman   = file.path(results_dir, "top200_spearman.txt"),  # Using top200 as proxy
  MX         = file.path(results_dir, "top500_MX.txt"),
  kTotal     = file.path(results_dir, "top500_WGCNA_kTotal.txt")
)

# Also check for the main output file
main_output_file <- file.path(results_dir, "BRCA_TCGA-DSMZ_HVG500_genes_MX_top500.txt")
if (file.exists(main_output_file)) {
  gene_files_top500$MX_main <- main_output_file
}

# =============================================================================
# LOAD GENE SETS
# =============================================================================

cat("Loading gene sets from feature selection output...\n")
gene_sets <- imap(gene_files_top500, function(path, name) {
  genes <- read_gene_list_txt(path)
  if (length(genes) == 0) {
    warning("No genes loaded from: ", path)
  } else {
    cat("  ", name, ": ", length(genes), " genes\n", sep = "")
  }
  genes
})

# Filter out empty sets
gene_sets <- gene_sets[map_int(gene_sets, length) > 0]

if (length(gene_sets) == 0) {
  stop("No gene sets loaded! Check that feature selection has been run.")
}

cat("\n")

# =============================================================================
# COMPUTE COVERAGE PER METHOD
# =============================================================================

cat("Computing PAM50 coverage for each method...\n")

# Assume all feature selection outputs use Ensembl IDs (based on fs_wcgna.R)
coverage_tbl <- imap_dfr(gene_sets, function(gs, name) {
  result <- pam50_coverage(
    gene_set = gs,
    pam50_ensembl = pam50_ensembl,
    pam50_symbols = pam50_symbols,
    gene_set_type = "ensembl"
  ) %>%
    mutate(method = name, .before = 1)
  
  cat("  ", name, ": ", result$pam50_in_set_n, " / ", result$pam50_size, 
      " PAM50 genes (", sprintf("%.1f", result$pam50_coverage_pc), "%)\n", sep = "")
  
  result
}) %>%
  arrange(desc(pam50_coverage), desc(pam50_in_set_n))

cat("\n")

# =============================================================================
# CREATE DETAILED MATCHES TABLE
# =============================================================================

# Expand matches into a long format for detailed analysis
matches_long <- imap_dfr(gene_sets, function(gs, name) {
  gs_std <- standardize_ensembl(gs)
  pam50_std <- standardize_ensembl(pam50_ensembl)
  inter <- intersect(gs_std, pam50_std)
  
  if (length(inter) > 0) {
    tibble(
      method = name,
      pam50_gene = sort(inter)
    )
  } else {
    tibble(
      method = character(0),
      pam50_gene = character(0)
    )
  }
})

# =============================================================================
# SUMMARY STATISTICS
# =============================================================================

summary_stats <- tibble(
  metric = c(
    "Total PAM50 genes",
    "Methods analyzed",
    "Mean coverage (%)",
    "Median coverage (%)",
    "Max coverage (%)",
    "Min coverage (%)",
    "Total unique PAM50 genes found"
  ),
  value = c(
    length(pam50_ensembl),
    nrow(coverage_tbl),
    mean(coverage_tbl$pam50_coverage_pc, na.rm = TRUE),
    median(coverage_tbl$pam50_coverage_pc, na.rm = TRUE),
    max(coverage_tbl$pam50_coverage_pc, na.rm = TRUE),
    min(coverage_tbl$pam50_coverage_pc, na.rm = TRUE),
    length(unique(matches_long$pam50_gene))
  )
)

# =============================================================================
# SAVE RESULTS
# =============================================================================

output_dir <- results_dir
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Main coverage table
coverage_file <- file.path(output_dir, "pam50_coverage_by_method.tsv")
write_tsv(coverage_tbl, coverage_file)
cat("Saved: ", coverage_file, "\n")

# Detailed matches
matches_file <- file.path(output_dir, "pam50_matches_per_method.tsv")
write_tsv(matches_long, matches_file)
cat("Saved: ", matches_file, "\n")

# Summary statistics
summary_file <- file.path(output_dir, "pam50_coverage_summary.tsv")
write_tsv(summary_stats, summary_file)
cat("Saved: ", summary_file, "\n")

# Human-readable summary
summary_txt_file <- file.path(output_dir, "pam50_coverage_summary.txt")
cat("=== PAM50 Coverage Summary ===\n\n", file = summary_txt_file)
cat("PAM50 signature size: ", length(pam50_ensembl), " genes\n\n", 
    file = summary_txt_file, append = TRUE)
cat("Coverage by method:\n", file = summary_txt_file, append = TRUE)
cat(capture.output(print(coverage_tbl, n = Inf)), sep = "\n", 
    file = summary_txt_file, append = TRUE)
cat("\n\nSummary statistics:\n", file = summary_txt_file, append = TRUE)
cat(capture.output(print(summary_stats)), sep = "\n", 
    file = summary_txt_file, append = TRUE)
cat("\nSaved: ", summary_txt_file, "\n")

# =============================================================================
# CONSOLE OUTPUT
# =============================================================================

cat("\n=== RESULTS ===\n\n")
print(coverage_tbl, n = Inf)
cat("\n=== SUMMARY ===\n\n")
print(summary_stats)
cat("\n")

# =============================================================================
# OPTIONAL: CREATE VISUALIZATION
# =============================================================================

if (requireNamespace("ggplot2", quietly = TRUE)) {
  library(ggplot2)
  
  p <- ggplot(coverage_tbl, aes(x = reorder(method, pam50_coverage_pc), 
                                 y = pam50_coverage_pc)) +
    geom_col(fill = "steelblue", alpha = 0.7) +
    geom_text(aes(label = paste0(pam50_in_set_n, "/", pam50_size)), 
              hjust = -0.1, size = 3) +
    coord_flip() +
    labs(
      x = "Method",
      y = "PAM50 Coverage (%)",
      title = "PAM50 Gene Coverage by Feature Selection Method"
    ) +
    theme_bw(base_size = 11) +
    theme(plot.title = element_text(hjust = 0.5))
  
  plot_file <- file.path(output_dir, "pam50_coverage_barplot.png")
  ggsave(plot_file, p, width = 10, height = 6, dpi = 300)
  cat("Saved: ", plot_file, "\n")
} else {
  cat("Note: Install ggplot2 for visualization\n")
}

cat("\n=== Analysis complete ===\n")

