profiles:
  nbl:
    tumour_rds: "data/nbl/raw_nbl_counts.rds"
    dsmz_rds: "data/dsmz/DSMZ_countFinal.rds"
    dsmz_meta_csv: "data/dsmz/DSMZ_metadata.csv"
    min_shared_genes: 5000
    tumour_label: "NBL_TUMOUR"
    dsmz_label: "DSMZ_NBL"
    dsmz_sample_col: "sample_name"
    dsmz_cellline_col: "Cell_Line"
    dsmz_filter_col: "Disease"
    dsmz_filter_values:
      - "Neuroblastoma"
    
