fastq_dir: "/home/chu25/data/ccle/fastq_files" #path to your FASTQ files
data_dir: "/home/chu25/data/ccle/fastq_files"
illumina_dir: "/home/chu25/illumina"

reference:
  hisat2_index: /home/chu25/data/HISAT2/genome/grch38/genome
  gtf: /home/chu25/data/GTF/Homo_sapiens.GRCh38.107.gtf

tools:
  trimmomatic: "/home/chu25/Trimmomatic-0.39/trimmomatic-0.39.jar"
  adapters: "/home/chu25/illumina/TruSeq3-PE.fa"


params:
  threads: 4
 
