executor: cluster-generic
cluster-generic-submit-cmd: "python profiles/slurm/slurm-submit.py"
jobs: 20
latency-wait: 60
rerun-incomplete: true
keep-going: true
printshellcmds: true
use-conda: true
conda-frontend: mamba

default-resources:
  - mem_mb=8000
  - runtime=60
  - cpus=1
  - gpu=0

