import os

# Snakefile to run MultiQC on Picard outputs

rule all:
    input:
        "/home/chu25/dsmz/results/multiqc/picard/multiqc_report.html"

rule multiqc_picard_summary:
    input:
        picard_dir = "/home/chu25/dsmz/results/picard"
    output:
        html = "/home/chu25/dsmz/results/multiqc/picard/multiqc_report.html"
    params:
        outdir = lambda wildcards, output: os.path.dirname(output.html)
    threads: 1
    shell:
        """
        echo "[INFO] Running MultiQC summary on Picard outputs..."
        multiqc {input.picard_dir} --outdir {params.outdir}
        """
