#!/usr/bin/env Rscript

# =============================================================================
# inspect_tumour_mapping.R
# =============================================================================
#
# DESCRIPTION
# -----------
# This script performs comprehensive diagnostic analysis of tumour-to-cell-line
# mapping results to identify failure modes, assess mapping confidence, and
# validate biological coherence. The inspection outputs facilitate quality
# control, troubleshooting, and refinement of the mapping pipeline.
#
#
# BIOLOGICAL CONTEXT: MAPPING QUALITY ASSESSMENT
# ----------------------------------------------
# Transcriptomic mapping of tumours to cell lines is inherently imperfect due
# to fundamental differences between in vivo tumours and in vitro cell lines.
# Cell lines undergo selection pressures during establishment and long-term
# culture that alter their transcriptional programmes compared to primary
# tumours. Despite these limitations, systematic mapping enables identification
# of cell line models that best recapitulate tumour molecular features.
#
# Systematic inspection of mapping results reveals several key aspects:
#
#   (1) Failure Modes: Patterns in incorrect mappings may indicate:
#       - Biological similarity between cancer types (e.g., shared developmental
#         origin or convergent transcriptional programmes)
#       - Gaps in cell line panel coverage for specific tumour subtypes
#       - Technical artefacts from batch effects or data quality issues
#
#   (2) Confidence Assessment: Mapping confidence varies across tumours due to:
#       - Tumour heterogeneity and admixture with stromal/immune cells
#       - Existence of multiple biologically similar cell line candidates
#       - Representation of tumour molecular subtypes in cell line collections
#
#   (3) Biological Coherence: Mappings should respect known biology:
#       - Tumours should preferentially map to cell lines of the same lineage
#       - Within-lineage mappings should reflect molecular subtype structure
#       - Graph-derived components should capture biologically meaningful groups
#
#
# DIAGNOSTIC ANALYSES PERFORMED
# -----------------------------
# Incorrect Mapping Analysis:
# For each tumour that maps to a cell line of a different cancer type, the
# script examines the lineage of the incorrectly matched cell line, the
# confidence metrics (delta, same-lineage fraction), and the distribution of
# correct-lineage cell lines in the top-10 rankings. Systematic patterns in
# incorrect mappings (e.g., all BRCA errors mapping to a specific lineage)
# may reveal biological relationships or data issues.
#
# Confidence Distribution Analysis:
# Confidence metrics quantify how definitively each tumour maps to its best
# match. Confidence delta measures the score separation between rank-1 and
# rank-10 matches, where low delta indicates multiple similarly-scored
# candidates. Same-lineage fraction measures the proportion of top-k matches
# from the correct cancer type, where low fractions suggest the tumour's
# transcriptomic profile is atypical for its lineage. Per-lineage statistics
# reveal whether certain cancer types have systematically lower confidence,
# potentially indicating inadequate cell line representation.
#
# Low Confidence Case Identification:
# Cases with confidence delta below a threshold (default: 0.03) are flagged
# for manual review. These may represent rare molecular subtypes not well-
# captured by standard cell lines, tumours with high stromal/immune content
# diluting the tumour signal, technical issues (low RNA quality, batch
# effects), or biologically ambiguous cases at subtype boundaries.
#
# Component-Level Mapping:
# When graph components are available, the script assesses whether tumours
# map coherently to biologically meaningful cell line clusters. This includes
# component usage (which components receive the most tumour mappings),
# per-lineage preferences (do cancer types show distinct component biases),
# and accuracy by component (are certain components associated with higher
# mapping accuracy).
#
# Top-k Lineage Consistency:
# For each tumour, the script evaluates how consistently the top-k cell lines
# belong to the expected cancer type. High consistency (all top-10 same
# lineage) indicates strong, unambiguous mapping. Mixed consistency suggests
# multiple lineages in the top-10, indicating potential biological similarity
# or subtype ambiguity. Low consistency suggests the tumour profile is
# atypical for its annotated lineage.
#
#
# INPUT REQUIREMENTS
# ------------------
# 1. Tumour mapping summary (--summary):
#    Per-tumour best match, scores, and confidence metrics generated by
#    score_tumour_cellline_mapping.R
#
# 2. Full rankings (--rankings):
#    Top-k cell lines per tumour with scores and lineage information,
#    enabling detailed analysis of ranking composition
#
# 3. Graph components (--components, optional):
#    Cell line component assignments from similarity graph analysis,
#    enabling component-level diagnostic analyses
#
#
# OUTPUT FILES
# ------------
# The script produces diagnostic tables and a summary report:
#
#   incorrect_mappings_analysis.tsv
#       Detailed analysis of each incorrect mapping including top-10 breakdown.
#
#   confidence_statistics.tsv
#       Per-lineage summary statistics for confidence metrics.
#
#   low_confidence_cases.tsv
#       Tumours with confidence delta below threshold, flagged for review.
#
#   component_usage.tsv
#       Summary of tumour mappings per graph component.
#
#   component_by_lineage.tsv
#       Cross-tabulation of tumour lineage and component assignment.
#
#   topk_lineage_consistency.tsv
#       Per-tumour assessment of lineage consistency in top-10 rankings.
#
#   score_statistics.tsv
#       Per-lineage summary of best-match score distributions.
#
#   INSPECTION_SUMMARY.md
#       Human-readable report summarising all diagnostic findings.
#
#
# USAGE EXAMPLE
# -------------
#   Rscript inspect_tumour_mapping.R \
#     --summary tumour_mapping_group_summary.tsv \
#     --rankings tumour_to_cellline_group_rankings.tsv \
#     --components pan_cancer_components.tsv \
#     --output-dir inspection
#
#
# DEPENDENCIES
# ------------
# R packages: data.table, ggplot2, optparse
#
# =============================================================================


# =============================================================================
# PACKAGE LOADING
# =============================================================================
# The script requires three R packages for its core functionality:
#
#   data.table: Provides efficient data manipulation capabilities through
#               its reference semantics and optimised grouping operations.
#               Essential for handling large-scale mapping results where
#               standard data.frame operations would be prohibitively slow.
#               Key functions used include fread() for fast file reading,
#               the := operator for in-place column assignment, and the
#               by= argument for grouped aggregations.
#
#   ggplot2:    The grammar of graphics implementation in R. While primarily
#               loaded for potential diagnostic visualisations, the current
#               script focuses on tabular outputs. Future extensions could
#               include confidence distribution plots and confusion matrices.
#
#   optparse:   Provides GNU-style command-line argument parsing, enabling
#               flexible script invocation with named parameters. This
#               facilitates integration into automated pipelines while
#               maintaining human-readable argument specification.
#
# The suppressPackageStartupMessages() wrapper prevents verbose loading
# messages that would clutter pipeline logs and interfere with the script's
# structured output reporting.
# -----------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(optparse)
})


# =============================================================================
# COMMAND-LINE ARGUMENT DEFINITIONS
# =============================================================================
# Command-line arguments enable flexible script execution across different
# datasets and analysis configurations. Each argument is defined with its
# expected type and a help string for user documentation.
#
# Required Arguments:
#   --summary:    Path to the tumour mapping summary file containing per-tumour
#                 best matches and confidence metrics. This is the primary input
#                 for most diagnostic analyses.
#
#   --rankings:   Path to the complete rankings file with top-k cell lines per
#                 tumour. Enables analysis of ranking composition and lineage
#                 consistency beyond just the top-1 match.
#
#   --output-dir: Directory for all output files. Created if it does not exist.
#
# Optional Arguments:
#   --components: Path to graph component assignments for cell lines. When
#                 provided, enables additional analyses of how tumours map
#                 to biologically-defined cell line clusters.
# -----------------------------------------------------------------------------

option_list <- list(
  make_option(c("--summary"), type = "character", default = NULL,
              help = "Path to tumour mapping summary TSV"),
  make_option(c("--rankings"), type = "character", default = NULL,
              help = "Path to tumour-to-cellline rankings TSV"),
  make_option(c("--components"), type = "character", default = NULL,
              help = "Path to graph components TSV"),
  make_option(c("--output-dir"), type = "character", default = NULL,
              help = "Output directory for inspection results")
)

# -----------------------------------------------------------------------------
# Parse arguments from command line
# The OptionParser object processes command-line inputs according to the
# defined option_list specification, returning a named list of argument values.
# -----------------------------------------------------------------------------

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)


# =============================================================================
# INPUT VALIDATION
# =============================================================================
# Validates that all required arguments are provided before proceeding with
# analysis. Early termination with an informative error message prevents
# confusing downstream failures from missing inputs.
#
# The output directory is created with recursive = TRUE to handle nested
# directory structures, and showWarnings = FALSE to suppress messages when
# the directory already exists.
# -----------------------------------------------------------------------------

if (is.null(opt$summary) || is.null(opt$rankings) || is.null(opt$`output-dir`)) {
  stop("--summary, --rankings, and --output-dir are required")
}

dir.create(opt$`output-dir`, recursive = TRUE, showWarnings = FALSE)

cat("========================================\n")
cat("TUMOUR MAPPING INSPECTION\n")
cat("========================================\n\n")


# =============================================================================
# STEP 1: LOAD INPUT DATA
# =============================================================================
# This step loads the pre-computed mapping results required for diagnostic
# analysis. The data.table fread() function provides fast reading of
# tab-separated files with automatic type inference.
#
# Summary Data Structure:
# The summary file contains one row per tumour with columns including:
#   - tumour_id:                   Unique identifier for each tumour sample
#   - tumour_lineage:              Cancer type annotation (e.g., BRCA, NBL)
#   - best_cell_line:              Identifier of the top-ranked cell line match
#   - best_cell_line_lineage:      Cancer type of the best-matched cell line
#   - best_score:                  Similarity score for the top-1 match
#   - is_correct:                  Boolean indicating lineage-concordant mapping
#   - confidence_delta:            Score difference between rank-1 and rank-10
#   - confidence_frac_same_lineage: Fraction of top-10 from same lineage
#
# Rankings Data Structure:
# The rankings file contains multiple rows per tumour (one per ranked cell
# line) with columns including:
#   - tumour:        Tumour identifier matching summary$tumour_id
#   - tum_lineage:   Tumour cancer type
#   - rank:          Position in the ranking (1 = best match)
#   - cell_line:     Cell line identifier
#   - cell_lineage:  Cancer type of the cell line
#   - score:         Similarity score for this tumour-cell line pair
#
# Components Data Structure (optional):
# When provided, contains cell line to graph component mappings:
#   - sample:    Cell line identifier
#   - component: Integer component assignment from graph clustering
# -----------------------------------------------------------------------------

cat("[1] Loading data...\n")

# Load the per-tumour mapping summary using fast file reading
summary <- fread(opt$summary)

# Load the complete rankings with all top-k matches per tumour
rankings <- fread(opt$rankings)

# Conditionally load component assignments if file path is provided and valid
# The is.null() check handles missing argument, file.exists() handles invalid path
if (!is.null(opt$components) && file.exists(opt$components)) {
  components <- fread(opt$components)
  cat("  Loaded components\n")
} else {
  components <- NULL
  cat("  No components file provided\n")
}

# Report data dimensions for verification
cat("  Summary: ", nrow(summary), " tumours\n", sep = "")
cat("  Rankings: ", nrow(rankings), " entries\n", sep = "")


# =============================================================================
# STEP 2: INCORRECT MAPPING ANALYSIS
# =============================================================================
# Incorrect mappings occur when a tumour's best-matching cell line originates
# from a different cancer type than the tumour itself. Analysing these cases
# reveals potential failure modes and biological relationships between cancer
# types.
#
# Biological Rationale:
# While lineage-discordant mappings are often considered errors, they can
# reflect genuine biological phenomena. For example:
#   - Tumours of shared developmental origin (e.g., neuroendocrine tumours
#     from different anatomical sites) may share transcriptional programmes
#   - Convergent evolution under similar selective pressures can produce
#     similar expression profiles across lineages
#   - Rare molecular subtypes may be better represented in cell line
#     collections of related cancer types
#
# Diagnostic Questions Addressed:
#   - Are incorrect mappings random or do they show systematic patterns?
#   - Do certain tumour subtypes consistently map to specific alternative
#     lineages?
#   - Are correct-lineage cell lines present in the top-10, suggesting
#     the error is marginal?
#   - Do low-confidence metrics predict incorrect mappings?
#
# The analysis extracts key metrics for each incorrect mapping and examines
# the composition of the top-10 rankings to determine whether correct-lineage
# alternatives were close contenders.
# -----------------------------------------------------------------------------

cat("\n[2] Analysing incorrect mappings...\n")

# Subset to only incorrectly mapped tumours using data.table filtering syntax
# The is_correct column is a boolean indicating whether tumour and cell line
# share the same cancer type annotation
incorrect <- summary[is_correct == FALSE]
cat("  Incorrect mappings: ", nrow(incorrect), "\n", sep = "")

# Extract key diagnostic fields for each incorrect mapping
# This creates a focused data.table with the most relevant columns for
# understanding why each mapping failed
incorrect_analysis <- incorrect[, .(
  tumour_id,
  tumour_lineage,
  best_cell_line,
  best_cell_line_lineage,
  best_score,
  confidence_delta,
  confidence_frac_same_lineage
)]

# Examine top-10 ranking composition for each incorrect mapping
# This reveals whether correct-lineage cell lines were close alternatives
# that narrowly missed being selected as the best match
for (i in seq_len(nrow(incorrect))) {
  # Get the tumour identifier for this incorrect mapping
  tum_id <- incorrect$tumour_id[i]
  
  # Extract the top-10 ranked cell lines for this tumour from the full
  # rankings table using data.table's efficient subsetting
  tum_ranks <- rankings[tumour == tum_id & rank <= 10]
  
  # Get the expected lineage for this tumour
  tum_lineage <- incorrect$tumour_lineage[i]

  # Count how many of the top-10 cell lines are from the correct lineage
  # This indicates whether the tumour's transcriptomic profile has any
  # affinity for its annotated cancer type
  n_correct <- sum(tum_ranks$cell_lineage == tum_lineage, na.rm = TRUE)
  
  # Add the count to the analysis table using := for in-place assignment
  incorrect_analysis[i, n_correct_in_top10 := n_correct]

  # Record all lineages present in the top-10 for pattern analysis
  # The semicolon-separated format enables downstream parsing and
  # identification of systematic lineage confusion patterns
  incorrect_analysis[i, top10_lineages := paste(tum_ranks$cell_lineage,
                                                 collapse = ";")]
}

# Write the incorrect mapping analysis to a tab-separated file
incorrect_file <- file.path(opt$`output-dir`, "incorrect_mappings_analysis.tsv")
fwrite(incorrect_analysis, file = incorrect_file, sep = "\t")
cat("  Saved to:", incorrect_file, "\n")

# Display cross-tabulation of true tumour lineage versus predicted cell
# line lineage to reveal systematic confusion patterns
# Rows represent tumour lineages, columns represent cell line lineages
# Off-diagonal entries indicate specific lineage pairs with mapping errors
cat("\n  Breakdown by tumour lineage:\n")
print(table(incorrect$tumour_lineage, incorrect$best_cell_line_lineage))


# =============================================================================
# STEP 3: CONFIDENCE DISTRIBUTION ANALYSIS
# =============================================================================
# Confidence metrics quantify the certainty of each tumour-to-cell-line
# mapping. Systematic analysis of these metrics across cancer types reveals
# whether certain lineages have inherently lower mapping confidence.
#
# Confidence Metrics Explained:
#
#   confidence_delta: The difference in similarity score between the rank-1
#   and rank-10 cell line matches. This measures how much better the best
#   match is compared to alternative candidates.
#     - High delta (>0.10): Strong preference for top match; unambiguous mapping
#     - Medium delta (0.03-0.10): Moderate confidence; top match is preferred
#       but alternatives exist
#     - Low delta (<0.03): Multiple similarly-scored candidates; mapping may
#       be sensitive to small data perturbations
#
#   confidence_frac_same_lineage: The fraction of top-10 cell lines that
#   share the same cancer type as the tumour. This measures lineage-specific
#   affinity.
#     - High fraction (>0.8): Tumour profile is typical for its lineage
#     - Medium fraction (0.4-0.8): Some cross-lineage similarity present
#     - Low fraction (<0.4): Tumour profile is atypical; may represent rare
#       subtype or potential annotation error
#
# Per-Lineage Interpretation:
# Lineages with systematically lower confidence metrics may indicate:
#   - Insufficient cell line representation for that cancer type
#   - Greater molecular heterogeneity within the lineage
#   - Stronger batch effects between tumour and cell line platforms
#   - Cell lines that have diverged significantly from primary tumours
# -----------------------------------------------------------------------------

cat("\n[3] Analysing confidence distributions...\n")

# Extract relevant columns for confidence analysis
# This creates a focused subset for computing per-lineage statistics
conf_stats <- summary[, .(
  lineage = tumour_lineage,
  confidence_delta,
  confidence_frac_same_lineage,
  is_correct
)]

# Compute summary statistics grouped by cancer lineage
# The by = lineage argument enables automatic aggregation within each group
conf_summary <- conf_stats[, .(
  # Sample size for this lineage
  n = .N,
  
  # Central tendency measures for confidence delta
  # Mean is sensitive to outliers while median is robust
  mean_delta = mean(confidence_delta, na.rm = TRUE),
  median_delta = median(confidence_delta, na.rm = TRUE),
  
  # Interquartile range bounds for confidence delta
  # Q25-Q75 captures the central 50% of the distribution
  q25_delta = quantile(confidence_delta, 0.25, na.rm = TRUE),
  q75_delta = quantile(confidence_delta, 0.75, na.rm = TRUE),
  
  # Mean same-lineage fraction across tumours of this type
  mean_frac_same = mean(confidence_frac_same_lineage, na.rm = TRUE),
  
  # Count of low-confidence cases using 0.03 threshold
  # These cases warrant manual review for potential mapping issues
  n_low_conf = sum(confidence_delta < 0.03, na.rm = TRUE)
), by = lineage]

# Write confidence statistics to output file
conf_file <- file.path(opt$`output-dir`, "confidence_statistics.tsv")
fwrite(conf_summary, file = conf_file, sep = "\t")
cat("  Saved to:", conf_file, "\n")


# =============================================================================
# STEP 4: LOW CONFIDENCE CASE IDENTIFICATION
# =============================================================================
# This step identifies tumours with confidence delta below a threshold,
# flagging them for manual review. The default threshold of 0.03 represents
# approximately the bottom quartile of typical confidence distributions,
# though optimal thresholds may vary by dataset.
#
# Biological and Technical Reasons for Low Confidence:
#
# 1. Rare Molecular Subtypes:
#    Tumours belonging to uncommon molecular subtypes may not be well-
#    represented in cell line collections. For example, claudin-low breast
#    cancers or mesenchymal glioblastomas may lack closely matching cell
#    line models.
#
# 2. Tumour Microenvironment Contamination:
#    Primary tumour samples contain variable proportions of stromal
#    fibroblasts, immune cells, and vascular endothelium. High non-tumour
#    content dilutes the tumour-specific signal and may cause the sample
#    to appear transcriptomically dissimilar from pure cell line cultures.
#
# 3. Technical Artefacts:
#    Low RNA quality, library preparation biases, or batch effects between
#    tumour and cell line datasets can introduce systematic differences
#    that obscure biological similarity.
#
# 4. Subtype Boundary Cases:
#    Tumours at the boundary between molecular subtypes may show mixed
#    characteristics, resulting in multiple similarly-scoring cell line
#    matches from different subtype-representative models.
#
# Manual review of these cases should consider the tumour's clinical
# annotation, histological subtype, and the biological relationship
# between the tumour and its candidate cell line matches.
# -----------------------------------------------------------------------------

cat("\n[4] Identifying low confidence cases...\n")

# Filter to tumours with confidence delta below the threshold
# The 0.03 threshold identifies approximately the lowest quartile of
# typical confidence distributions
low_conf <- summary[confidence_delta < 0.03]
cat("  Low confidence cases: ", nrow(low_conf), "\n", sep = "")

# Always write the low-confidence file (even if empty) to satisfy pipeline checks
low_conf_file <- file.path(opt$`output-dir`, "low_confidence_cases.tsv")
fwrite(low_conf[, .(tumour_id, tumour_lineage, best_cell_line_lineage,
                    is_correct, confidence_delta, confidence_frac_same_lineage)],
       file = low_conf_file, sep = "\t")
cat("  Saved to:", low_conf_file, "\n")


# =============================================================================
# STEP 5: COMPONENT-LEVEL MAPPING ANALYSIS
# =============================================================================
# When graph components are available, this step analyses how tumours
# distribute across cell line clusters. Graph-derived components partition
# cell lines into groups representing stable transcriptional states,
# typically corresponding to lineage, molecular subtype, or shared
# biological programmes.
#
# Biological Rationale:
# Cell line similarity graphs constructed from expression correlation or
# other metrics naturally cluster into communities (components) reflecting
# shared transcriptional identity. These components often correspond to:
#   - Cancer type (lineage-specific components)
#   - Molecular subtypes within a lineage (e.g., luminal vs basal breast)
#   - Shared biological programmes across lineages (e.g., EMT, stemness)
#
# Diagnostic Questions Addressed:
#
#   Component Usage: Which components receive the most tumour mappings?
#   Components with many mappings contain broadly representative cell lines,
#   while components with few mappings may contain specialised models for
#   rare tumour subtypes.
#
#   Per-Lineage Preferences: Do cancer types show distinct component biases?
#   Ideally, tumours of a given lineage should preferentially map to
#   lineage-specific components. Cross-lineage component usage may indicate
#   shared biology or inadequate cell line coverage.
#
#   Accuracy by Component: Are certain components associated with higher
#   mapping accuracy? Components with low accuracy may contain cell lines
#   that have diverged from their originating tumour types.
# -----------------------------------------------------------------------------

if (!is.null(components)) {
  cat("\n[5] Analysing component-level mapping...\n")

  # Create a named vector mapping cell line identifiers to component numbers
  # This enables fast lookup of component assignment for any cell line
  comp_map <- setNames(components$component, components$sample)

  # Assign component to each tumour based on its top-1 cell line match
  # The := operator performs efficient in-place column addition
  summary[, top1_component := comp_map[best_cell_line]]

  # Summarise component usage across all tumours
  # This reveals which cell line clusters are most frequently matched
  comp_usage <- summary[, .(
    # Number of tumours mapping to this component
    n_tumours = .N,
    
    # Number of correct (lineage-concordant) mappings within this component
    n_correct = sum(is_correct),
    
    # Mean confidence delta for mappings to this component
    # Low values may indicate the component contains ambiguously similar lines
    mean_confidence = mean(confidence_delta, na.rm = TRUE)
  ), by = top1_component]

  # Write component usage summary
  comp_file <- file.path(opt$`output-dir`, "component_usage.tsv")
  fwrite(comp_usage, file = comp_file, sep = "\t")
  cat("  Saved to:", comp_file, "\n")

  # Cross-tabulate tumour lineage and component assignment
  # This reveals lineage-specific component preferences and identifies
  # cases where tumours map to unexpected components
  comp_by_lineage <- summary[, .(
    n = .N
  ), by = .(tumour_lineage, top1_component)]

  comp_by_lineage_file <- file.path(opt$`output-dir`, "component_by_lineage.tsv")
  fwrite(comp_by_lineage, file = comp_by_lineage_file, sep = "\t")
  cat("  Saved to:", comp_by_lineage_file, "\n")
}


# =============================================================================
# STEP 6: TOP-K LINEAGE CONSISTENCY ANALYSIS
# =============================================================================
# This step evaluates how consistently the top-k cell line matches belong
# to the expected cancer type for each tumour. Lineage consistency provides
# a measure of mapping robustness beyond just the top-1 accuracy.
#
# Interpretation of Consistency Levels:
#
#   High Consistency (all top-10 same lineage):
#   The tumour's transcriptomic profile is clearly and unambiguously
#   associated with its annotated cancer type. Cell lines of that type
#   form a distinct cluster in expression space, and the mapping is
#   robust to small perturbations in scoring.
#
#   Mixed Consistency (some top-10 from different lineages):
#   Multiple cancer types are represented in the top-10 matches. This
#   pattern may indicate:
#     - Biological similarity between the lineages involved
#     - Tumour at a molecular subtype boundary
#     - Tumour with atypical features for its annotated lineage
#     - Potential annotation error in tumour or cell line metadata
#
#   Low Consistency (most top-10 from different lineages):
#   The tumour profile is highly atypical for its annotated lineage.
#   These cases warrant careful review of the tumour's clinical and
#   histological annotations.
#
# Clinical Relevance:
# Tumours with high lineage consistency are better candidates for cell
# line-based functional studies, as the mapping is more certain. Tumours
# with mixed consistency may benefit from validation using multiple cell
# line models representing the different lineages in their top-k.
# -----------------------------------------------------------------------------

cat("\n[6] Analysing top-k lineage consistency...\n")

# Compute lineage consistency metrics for each tumour
# The analysis is limited to top-10 rankings using rank <= 10
topk_consistency <- rankings[rank <= 10, .(
  # Total number of cell lines in the top-k (should be 10 if rankings complete)
  n_total = .N,
  
  # Count of cell lines matching the tumour's lineage
  # Compares cell_lineage (cell line annotation) to tum_lineage (tumour annotation)
  n_same_lineage = sum(cell_lineage == tum_lineage, na.rm = TRUE),
  
  # Fraction of top-k from the same lineage
  # Equivalent to confidence_frac_same_lineage but computed independently
  frac_same = mean(cell_lineage == tum_lineage, na.rm = TRUE)
), by = .(tumour, tum_lineage)]

# Flag tumours with perfect consistency (all top-10 from same lineage)
# These represent the most confident and robust mappings
topk_consistency[, all_same := n_same_lineage == n_total]

# Write lineage consistency results
consistency_file <- file.path(opt$`output-dir`, "topk_lineage_consistency.tsv")
fwrite(topk_consistency, file = consistency_file, sep = "\t")
cat("  Saved to:", consistency_file, "\n")

# Report count of perfectly consistent mappings
cat("\n  Tumours with all top-10 from same lineage: ",
    sum(topk_consistency$all_same), " / ", nrow(topk_consistency), "\n", sep = "")


# =============================================================================
# STEP 7: SCORE DISTRIBUTION ANALYSIS
# =============================================================================
# This step analyses the distribution of best-match similarity scores
# across cancer types. Score distributions reveal how well tumours match
# their best cell line candidates and whether certain lineages have
# systematically higher or lower match quality.
#
# Interpreting Score Distributions:
#
#   High Mean/Median Scores:
#   Tumours of this lineage tend to have cell lines that closely match
#   their transcriptomic profiles. This suggests good cell line coverage
#   and/or high molecular homogeneity within the lineage.
#
#   Low Mean/Median Scores:
#   Tumours poorly match even their best cell line candidates. This may
#   indicate:
#     - Insufficient cell line representation for this cancer type
#     - Cell lines that have diverged significantly from primary tumours
#     - High tumour heterogeneity or microenvironment contamination
#     - Technical batch effects between tumour and cell line platforms
#
#   Wide Score Range (large max-min difference):
#   High variability in matching quality within the lineage. Some tumours
#   have excellent cell line models while others do not.
#
# Relationship to Accuracy:
# The mean_correct column reports the fraction of tumours with lineage-
# concordant top-1 mappings. Comparing this to score statistics reveals
# whether low scores predict incorrect mappings for a given lineage.
# -----------------------------------------------------------------------------

cat("\n[7] Analysing score distributions...\n")

# Extract best scores and correctness indicators grouped by lineage
score_stats <- summary[, .(
  lineage = tumour_lineage,
  best_score,
  is_correct
)]

# Compute per-lineage summary statistics for best-match scores
score_summary <- score_stats[, .(
  # Sample size
  n = .N,
  
  # Central tendency of best-match scores
  mean_score = mean(best_score, na.rm = TRUE),
  median_score = median(best_score, na.rm = TRUE),
  
  # Score range indicating variability in matching quality
  min_score = min(best_score, na.rm = TRUE),
  max_score = max(best_score, na.rm = TRUE),
  
  # Top-1 accuracy (fraction of correct mappings)
  # Enables correlation analysis between scores and accuracy
  mean_correct = mean(is_correct, na.rm = TRUE)
), by = lineage]

# Write score statistics to output file
score_file <- file.path(opt$`output-dir`, "score_statistics.tsv")
fwrite(score_summary, file = score_file, sep = "\t")
cat("  Saved to:", score_file, "\n")


# =============================================================================
# STEP 8: GENERATE SUMMARY REPORT
# =============================================================================
# This step produces a human-readable Markdown report that consolidates
# all diagnostic findings for rapid assessment of mapping quality. The
# report serves as the primary entry point for quality control review
# and provides an overview without requiring examination of individual
# output files.
#
# Report Sections:
#
#   Overall Performance: Global metrics including total tumour count,
#   top-1 accuracy, incorrect mapping count, and mean confidence measures.
#   These provide an immediate assessment of mapping success.
#
#   Per-Lineage Performance: The confidence statistics table showing
#   sample size, confidence delta distribution, and low-confidence counts
#   for each cancer type. Enables identification of lineages requiring
#   attention.
#
#   Incorrect Mappings: Count and cross-tabulation of incorrect mappings
#   by tumour and cell line lineage. Reveals systematic confusion patterns
#   between cancer types.
#
#   Low Confidence Cases: Count and threshold used for identifying cases
#   requiring manual review.
# -----------------------------------------------------------------------------

cat("\n[8] Creating inspection summary...\n")

# Construct the Markdown-formatted summary report
# The paste0() function concatenates strings without separators
summary_text <- paste0(
  "# Tumour Mapping Inspection Summary\n\n",
  
  # Overall performance metrics section
  "## Overall Performance\n",
  "- Total tumours: ", nrow(summary), "\n",
  "- Top-1 accuracy: ", round(mean(summary$is_correct) * 100, 2), "%\n",
  "- Incorrect mappings: ", sum(!summary$is_correct), "\n",
  "- Mean confidence delta: ", round(mean(summary$confidence_delta, na.rm = TRUE), 3), "\n",
  "- Mean top-10 same-lineage fraction: ",
      round(mean(summary$confidence_frac_same_lineage, na.rm = TRUE), 3), "\n\n",
  
  # Per-lineage confidence statistics
  # capture.output() converts the print output to character strings
  "## Per-Lineage Performance\n",
  paste(capture.output(print(conf_summary)), collapse = "\n"), "\n\n",
  
  # Incorrect mapping breakdown
  "## Incorrect Mappings\n",
  ifelse(nrow(incorrect) > 0,
    paste0("- Count: ", nrow(incorrect), "\n",
           "- Breakdown:\n",
           paste(capture.output(print(table(incorrect$tumour_lineage,
                                            incorrect$best_cell_line_lineage))),
                 collapse = "\n")),
    "- None\n"),
  
  # Low confidence case summary
  "\n\n## Low Confidence Cases\n",
  "- Count: ", nrow(low_conf), "\n",
  "- Threshold: confidence_delta < 0.03\n"
)

# Write the summary report to a Markdown file
report_file <- file.path(opt$`output-dir`, "INSPECTION_SUMMARY.md")
writeLines(summary_text, report_file)
cat("  Saved to:", report_file, "\n")


# =============================================================================
# EXECUTION SUMMARY
# =============================================================================
# Final output confirming successful completion and indicating where output
# files have been saved. This structured termination message facilitates
# integration with pipeline logging systems.
# -----------------------------------------------------------------------------

cat("\n========================================\n")
cat("INSPECTION COMPLETE\n")
cat("========================================\n")
cat("\nOutput files saved to:", opt$`output-dir`, "\n")